spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/showup2move
spring.datasource.username=pixelstudent
spring.datasource.password=parolapixel
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=1234